# Generated by Django 3.1.4 on 2020-12-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0002_auto_20201227_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(to='test_blog.Tag'),
        ),
    ]
